#!/bin/bash
# Bash wrappers for docker run commands
alias dl='docker ps -l -q'

# copied from jessfrazz
dcleanup() {
    local containers
    containers=( $(docker ps -aq 2>/dev/null) )
    docker rm "${containers[@]}" 2>/dev/null
    local volumes
    volumes=( $(docker ps --filter status=exited -q 2>/dev/null) )
    docker rm -v "${volumes[@]}" 2>/dev/null
    local images
    images=( $(docker images --filter dangling=true -q 2>/dev/null) )
    docker rmi "${images[@]}" 2>/dev/null
}

dpurge() {
  docker rmi --force $(docker images -q)
}

# copied from jessfrazz
del_stopped() {
    local name=$1
    local state
    state=$(docker inspect --format "{{.State.Running}}" "$name" 2>/dev/null)
    if [[ "$state" == "false" ]]; then
        docker rm "$name"
    fi
}

custom_zim() {
    del_stopped zim
    KEY=$(xauth list  |grep $(hostname) | awk '{ print $3 }' | head -n 1)
    DCK_HOST=docker-zim
    xauth add $DCK_HOST/unix:0 . $KEY
    docker run --rm -it -d \
       --user=$(id -u $(whoami)) \
       -e DISPLAY=unix$DISPLAY \
       -v /tmp/.X11-unix:/tmp/.X11-unix \
       -v $HOME/.Xauthority:/tmp/.Xauthority \
       -v $HOME/Documents/Notebooks/Notes:/home/zim/Notebooks/Notes \
       --name zim \
       -h $DCK_HOST \
       -e XAUTHORITY=/tmp/.Xauthority  \
       murtis/zimwiki
}

jupyter_notebook() {
  docker run -it --rm \
  -p 8888:8888 \
  -v ~/Documents/ipynb:/home/jovyan/work \
  jupyter/scipy-notebook
}

murtbuntu() {
  docker run -it --rm \
    -v ~/sbox:/home/user/sbox/ \
    murtis/murtbuntu
}

ros_ewok() {
  docker run --rm -it \
    --name ros_ewok \
    murtis/ewok_example
}

pubg_automontage() {
  docker run --rm -it \
    --name pubg_automontage \
    -v `pwd`:/usr/io \
    murtis/pubg_automontage:latest
}

ctop() {
  docker run --rm -ti \
    --name=ctop \
    -v /var/run/docker.sock:/var/run/docker.sock \
    quay.io/vektorlab/ctop:latest

}

flight_review() {
  docker run --rm \
    --name flight_review \
    --network=host \
    murtis/flight_review
}

alias buildfarm='docker-compose -f ~/projects/buildfarm/buildfarm.yml up'
