# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh


# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# has a sweet time field
#ZSH_THEME="fletcherm"
# nice, super minimal design
#ZSH_THEME="nicoulaj"
# requires install
# git clone https://github.com/geometry-zsh/geometry.git $HOME/.oh-my-zsh/custom/themes/geometry
#ZSH_THEME="geometry/geometry"

# requires install
# git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k
ZSH_THEME="powerlevel10k/powerlevel10k"
POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="▶ "
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
DEFAULT_USER="murt"
POWERLEVEL9K_TIME_FOREGROUND='white'
POWERLEVEL9K_TIME_BACKGROUND='black'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(time dir user)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status virtualenv vcs)
POWERLEVEL9K_STATUS_OK=false

if [[ -o login ]]; then
  ZSH_THEME="nicoulaj"
fi

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"


# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=1

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Disable marking untracked files under VCS as dirty. This makes repository
# status check for large repositories much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(z git mercurial zsh-autosuggestions autojump command-not-found python pip github gnu-utils history-substring-search zsh-syntax-highlighting colored-man-pages catimg docker)

bindkey '^ ' autosuggest-accept

source $ZSH/oh-my-zsh.sh

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=6"
setopt HIST_IGNORE_SPACE
setopt histignorespace

if [ -f ~/.environment ]; then source ~/.environment; fi
if [ -f ~/.aliases ]; then source ~/.aliases; fi
if [ -f ~/.devpaths ]; then source ~/.devpaths; fi
if [ -f ~/.dockerfuncs ]; then source ~/.dockerfuncs; fi
if [ -f ~/.work_rc ]; then source ~/.work_rc; fi

# Toggle caps lock
#/usr/bin/setxkbmap -option "caps:swapescape"

alias nmap='noglob nmap'
alias calc='noglob calc'
alias rsync='noglob rsync'
alias rg='noglob rg'

# BAZEL AUTOCOMPLETE
# This way the completion script does not have to parse Bazel's options
# repeatedly.  The directory in cache-path must be created manually.
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache

# Automatically run tree after cd
function chpwd() {
    emulate -L zsh
    tree -L 1
}

if [ $TILIX_ID ]; then
    source /etc/profile.d/vte.sh
fi
