FROM murtbuntu
MAINTAINER Curtis Muntz <cmuntz@outlook.com>

RUN wget https://www.stereolabs.com/developers/downloads/ZED_SDK_Linux_Ubuntu16_v2.1.2.run
RUN chmod +x ZED_SDK_Linux_Ubuntu16_v2.1.2.run


CMD "zsh"
