#!/bin/bash
export GOPATH=$HOME/go

# Dev aliases
alias mi='cmake .. && make install -j'
alias makerton='make -j4'
alias bb='bazel build'
alias buildifier='~/go/bin/buildifier'

# Other
alias u='cd ..'
alias ls=' ls --color=always'
alias ll='ls -alF'
alias la='ls -A'
alias l='ll'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

alias git_delete_merged='git branch --merged | egrep -v "(^\*|master|dev)" | xargs git branch -d'

# call tree when cd s called
function cd {
    builtin cd "$@" && tree -L 1
}

# echos the ip address that is used to get to the internet. Note that this might fail in the case
# that multiple addresses can get to 8.8.8.8
function murtip () {
  local ip_rt=$(ip route get 8.8.8.8 | head -1 | cut -d' ' -f8)
  echo $ip_rt
}

function murtiface () {
  local ip_rt=$(ip route get 8.8.8.8 | head -1 | cut -d' ' -f5)
  echo $ip_rt
}

alias swapesc='/usr/bin/setxkbmap -option "caps:swapescape"'
