#!/bin/bash
export GOPATH=$HOME/go

# Dev aliases
alias mi='cmake .. && make install -j'
alias makerton='make -j4'
alias bb='bazel build'
alias buildifier='~/go/bin/buildifier'

# Other
alias u='cd ..'

if [ -n "$ZSH_VERSION" ]; then
  # bat: https://github.com/sharkdp/bat
  alias cat='bat'
  # lsd: https://github.com/Peltoche/lsd
  alias ls='lsd'
fi


alias ls=' ls --color=always'
alias ll='ls -alF'
alias la='ls -A'
alias l='ll'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

alias git_delete_merged='git branch --merged | egrep -v "(^\*|master|dev)" | xargs git branch -d'

# call tree when cd s called
#function cd {
#    builtin cd "$@" && tree -L 1
#}

# echos the ip address that is used to get to the internet. Note that this might fail in the case
# that multiple addresses can get to 8.8.8.8
function murtip () {
  local ip_rt=$(ip route get 8.8.8.8 | head -1 | cut -d' ' -f8)
  echo $ip_rt
}

function murtiface () {
  local ip_rt=$(ip route get 8.8.8.8 | head -1 | cut -d' ' -f5)
  #local ip_rt=$(ip route get "optitrack-server-hyperv.local" |head -1 | cut -d' ' -f5)
  echo $ip_rt
}

function screen_record () {
  # requires ffmpeg system installed =(
  # TODO(murt) move this into a dockerfile somehow...
  if [ $# -eq 0 ]; then
    echo "Usage: screen_record [OUTPUT_FILENAME].mkv"
    return 1
  fi
  local resolution=$(xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/')
  ffmpeg -framerate 25 -video_size $resolution -f x11grab -i :0.0 -f alsa -ac 2 -i pulse -vcodec libx264 -crf 0 -preset ultrafast $1
}


alias swapesc='/usr/bin/setxkbmap -option "caps:swapescape"'
alias ninja-ccache='PATH=/usr/lib/ccache:$PATH ninja'


function mount_nas() {
  local nas_ip=$1
  sudo mount -vvv -t nfs $nas_ip:/mnt/WD_5400_SATA/MurtNFS /mnt/freenas
}

alias mkderp='mkdir -p'

# to emulate armv7hf... note that this requires the linaro downlaoded and extracted to ~/murt/ext
alias qemu-rpi='qemu-arm -L /home/murt/murt/ext/gcc-linaro-5.3.1-2016.05-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/libc'

alias gdom='git diff origin/master'
