#!/bin/bash

# python
export PYTHONSTARTUP=~/.pythonrc

# go
export PATH=$PATH:/usr/local/go/bin

# cuda
export CUDA_HOME=/usr/local/cuda
export PATH=${CUDA_HOME}/bin:${PATH}
export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${CUDA_HOME}/lib64/stubs:$LD_LIBRARY_PATH
