#!/bin/bash

# python
export PYTHONPATH=$PYTHONPATH:$HOME/murt/mython
export PYTHONSTARTUP=~/.pythonrc

# go
export PATH=$PATH:/usr/local/go/bin

# cuda
#export CUDA_HOME=/usr/local/cuda-8.0
#export PATH=${CUDA_HOME}/bin:${PATH}
#export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:$LD_LIBRARY_PATH

